version: "3.7"

services:
  eureka-server:
    container_name: eureka
    image: eureka-server:latest
    ports:
      - "8761:8761"
    networks:
      - backend

  api-gateway:
    container_name: api-gateway
    image: api-gateway:latest
    hostname: "api-gateway"
    ports:
      - "8080:8080"
    environment:
      - eureka.client.serviceUrl.defaultZone=http://eureka-server:8761/eureka/
      - eureka.instance.preferIpAddress=true
    depends_on:
      - eureka-server
    networks:
      - backend

  videogame-service:
    container_name: videogame-service
    image: videogame-service:latest
    hostname: "videogame-service"
    ports:
      - "8443:8443"
    environment:
      - eureka.client.serviceUrl.defaultZone=http://eureka-server:8761/eureka/
      - eureka.instance.preferIpAddress=true
    depends_on:
      - eureka-server
    networks:
      - backend

  movie-service:
    container_name: movie-service
    image: movie-service:latest
    hostname: "movie-service"
    ports:
      - "8088:8088"
    environment:
      - eureka.client.serviceUrl.defaultZone=http://eureka-server:8761/eureka/
      - eureka.instance.preferIpAddress=true
    depends_on:
      - eureka-server
    networks:
      - backend

networks:
  backend: